### ISSUE TITLE
[Bug] ERROR Subject Area

### ISSUE THREAD

**Issue by SouthernPolaris** [compsci-adl/mytimetable#24]
### Description of the Bug

Error Subject Area appears as a selectable option in subject area. Additionally, WDC seems to be the course categorised under ERROR. There are 5 different variants of WDC labelled as follows:
ERROR {COURSE_ID} - Web and Database Computing

Additionally, each but the first WDC option is appended by a roman numeral from II - V

### Reproduction Steps

Appears right after git clone and running via the instructions in the README

### Expected Behaviour

Only valid courses should appear

### Additional Notes

![errorSubjectArea](https://github.com/user-attachments/assets/56bbf91d-3037-4718-8fe0-2dad80695d5f)

**Comment by phoenixpereira** [comment]
This seems like an issue with the mock data as this issue isn't present on production.
