### ISSUE TITLE
[Bug] Semester 1 Option Adds Courses Between July and October

### ISSUE THREAD

**Issue by SouthernPolaris** [compsci-adl/mytimetable#25]
### Description of the Bug

When selecting courses with semester 1 as an option, for example ADDS, the courses are added between the July - October range, which is semester 2

### Reproduction Steps

Right after a fresh clone. Select semester 1 -> Chose ADDS as an example, but also tried Grand Challenges right after (same issue)

### Expected Behaviour

It should add courses between the February - June range

**Comment by phoenixpereira** [comment]
Similar to [#24](https://github.com/compsci-adl/mytimetable/issues/24#issuecomment-2480413947), this is occuring because it's using the mock data.
